name: Push to Amazon ECR Docker image

on:
  workflow_call:

env:
  ECR_REPOSITORY: o0u3o2v9
  CONTAINER_NAME: events-backend
  AWS_REGION: us-east-1

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-deploy-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws ecr-public get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin public.ecr.aws/$ECR_REPOSITORY
          docker build -t $CONTAINER_NAME .
          docker tag $CONTAINER_NAME:latest public.ecr.aws/$ECR_REPOSITORY/$CONTAINER_NAME:$IMAGE_TAG
          docker push public.ecr.aws/$ECR_REPOSITORY/$CONTAINER_NAME:$IMAGE_TAG

      - name: Build and deploy AWS infrastructure
        id: build-deploy-infrastructure
        run: |
          npm install 
          cdk synth
          cdk bootstrap
          cdk deploy
