name: Pipeline Events Backend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  nodejs-workflow:
    name: Nodejs Test and Build
    uses: ./.github/workflows/node.js.yml

  aws-workflow:
    name: Build and Deploy container to ACR
    needs: nodejs-workflow
    uses: ./.github/workflows/aws.yml
    secrets: inherit
