name: Pipeline Events Backend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  call-nodejs-workflow:
    uses: ./.github/workflows/node.js.yml
  call-aws-workflow:
    uses: ./.github/workflows/node.js.yml
