name: Pipeline Events Backend

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ env.AWS_REGION }}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  nodejs-workflow:
    name: Nodejs Test and Build
    uses: ./.github/workflows/node.js.yml

  aws-workflow:
    name: Build and Deploy container to ACR
    needs: nodejs-workflow
    uses: ./.github/workflows/aws.yml
